### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by Khabibullin543** [laxeye/zga#1]
Hello! Сould you tell me, please, how to fix this error?

(zga) khabibullinnr@microbgenome:~/233.09_the_first_run$ zga -1 233090_S22_L001_R1_001.fastq.gz -2 233090_S22_L001_R2_001.fastq.gz -o my_assembly
2023-02-22 11:49:25,628 - INFO - ZGA ver. 0.0.9post2
2023-02-22 11:49:25,628 - INFO - Full log location: /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/zga.log
2023-02-22 11:49:25,628 - INFO - Checking input files.
2023-02-22 11:49:25,628 - INFO - Read quality control started
2023-02-22 11:49:28,918 - INFO - Reads processing started
2023-02-22 11:49:28,918 - INFO - Trimming and filtering paired end reads
2023-02-22 11:49:36,965 - INFO - Merging paired-end reads.
2023-02-22 11:49:42,996 - INFO - Read processing finished
2023-02-22 11:49:42,996 - INFO - Assembling started
2023-02-22 11:49:47,411 - ERROR - Error during execution of: unicycler -o /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly -t 1 --mode normal -1 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u1.fq.gz -2 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u2.fq.gz -s /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.merged.fq.gz
2023-02-22 11:49:47,412 - INFO - Please see the logfile for additional information: /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/zga.log
2023-02-22 11:49:47,412 - ERROR - Genome assembly finished with errors.
2023-02-22 11:49:47,412 - ERROR - Plese check /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly/unicycler.log for more information.
Traceback (most recent call last):
  File "/home/MZRF/khabibullinnr/miniconda3/envs/zga/bin/zga", line 10, in <module>
    sys.exit(main())
  File "/home/MZRF/khabibullinnr/miniconda3/envs/zga/lib/python3.10/site-packages/zga/zga.py", line 1196, in main
    args.genome = assemble(args, reads, estimated_genome_size)
  File "/home/MZRF/khabibullinnr/miniconda3/envs/zga/lib/python3.10/site-packages/zga/zga.py", line 857, in assemble
    assembly = unicycler_assemble(args, reads, aslydir)
  File "/home/MZRF/khabibullinnr/miniconda3/envs/zga/lib/python3.10/site-packages/zga/zga.py", line 844, in unicycler_assemble
    raise Exception("Extermal software error")
Exception: Extermal software error

**Comment by laxeye** [comment]
Hi @Khabibullin543 
Could you show the content of unicycler log file (/home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly/unicycler.log)?

**Comment by Khabibullin543** [comment]
Starting Unicycler (2023-02-22 11:49:43)
----------------------------------------
    Welcome to Unicycler, an assembly pipeline for bacterial genomes. Since you provided only short reads, Unicycler will essentially function as a SPAdes-optimiser. It will try many k-mer sizes, choose the best based on contig length and graph connectivity, and scaffold the graph using SPAdes repeat resolution.
    For more information, please see https://github.com/rrwick/Unicycler

Command: /home/MZRF/khabibullinnr/miniconda3/envs/zga/bin/unicycler -o /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly -t 1 --mode normal -1 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u1.fq.gz -2 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u2.fq.gz -s /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.merged.fq.gz

Unicycler version: v0.4.4
Using 1 thread

Making output directory:
  /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly

Dependencies:
  Program         Version   Status  
  spades.py       3.14.1    good    
  racon                     not used
  makeblastdb     2.13.0+   good    
  tblastn         2.13.0+   good    
  bowtie2-build   2.5.1     good    
  bowtie2         2.5.1     good    
  samtools        1.16.1    good    
  java            17.0.5    good    
  pilon           1.24      good    
  bcftools                  not used


SPAdes read error correction (2023-02-22 11:49:47)
--------------------------------------------------
    Unicycler uses the SPAdes read error correction module to reduce the number of errors in the short read before SPAdes assembly. This can make the assembly faster and simplify the assembly graph structure.

Command: /home/MZRF/khabibullinnr/miniconda3/envs/zga/bin/spades.py -1 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u1.fq.gz -2 /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.u2.fq.gz -s /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/reads/lib1.merged.fq.gz -o /home/MZRF/khabibullinnr/233.09_the_first_run/my_assembly/assembly/spades_assembly/read_correction --threads 1 --only-error-correction
Error: SPAdes encountered an error: Traceback (most recent call last):
